### PR TITLE
A non-exhaustive set of possible registries

### PR DESCRIPTION
**Pull request by brentzundel**
This PR is based on #85.
It builds on PR #98 to add a non-exhaustive set of possible registries the WG may produce.

***
<a href="https://pr-preview.s3.amazonaws.com/brentzundel/vc-wg-charter/pull/99.html" title="Last updated on Mar 8, 2022, 6:53 PM UTC (74db552)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-wg-charter/99/bb419e2...brentzundel:74db552.html" title="Last updated on Mar 8, 2022, 6:53 PM UTC (74db552)">Diff</a>

### CODE REVIEW

**Review by msporny — CHANGES_REQUESTED** [review]
Overall, supportive, except for one confusing sentence detailed here: https://github.com/w3c/vc-wg-charter/pull/98#pullrequestreview-903427959

**Comment by brentzundel** [comment]
> Overall, supportive, except for one confusing sentence detailed here: [#98 (review)](https://github.com/w3c/vc-wg-charter/pull/98#pullrequestreview-903427959)

in order to keep this PR simple, I have moved that line to PR #101

**Review by selfissued — CHANGES_REQUESTED** [review]
Listing the possible registries is unnecessary and will likely just slow down finishing the charter as people kibitz about which possible registries are to be listed and not.  Let's simply close this PR without merging it as https://github.com/w3c/vc-wg-charter/pull/98 already does the needed job well.

**Comment by kdenhartog** [comment]
> Listing the possible registries is unnecessary and will likely just slow down finishing the charter as people kibitz about which possible registries are to be listed and not. Let's simply close this PR without merging it as #98 already does the needed job well.

+1 to this approach - I don't think we need to state which registries are going to be defined and it allows the WG to establish them as we gain a clearer understanding of which properties will be required versus optional as well as which conditional normative documents will be ready to standardize then we can decide which registry tables make the most sense.

**Review by iherman — APPROVED** [review]

**Review by OR13 — APPROVED** [review]

**Review by awoie — CHANGES_REQUESTED** [review]
if we add registries, we should add that the registration process is permissive.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2022-03-09-vcwg#section1-3) on 2022-03-09

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 1.3. A non-exhaustive set of possible registries (pr vc-wg-charter#99)

_See github pull request [vc-wg-charter#99](https://github.com/w3c/vc-wg-charter/pull/99)._




**Brent Zundel:** 99 steals the table from 95, removes the input table column and says we might do some or all, its very hand-wavy.  

**Manu Sporny:** in all the other sections of the charter, we have tried to exhaustively list the documents in the group to be clear on things we want to work on. i think this is a good idea for registries too, so AC reviewers get an understanding of our intent..  
… this PR highlights a number of registries that a number of us feel are important, this PR tries to be explicit which i think is a good thing..  

**Kyle Den Hartog:** i think its better not to be explicit because it buys us time, and allows us to re-split if we find there's a better arch pattern for this, instead of leading with that expectation. This expectation could bite us. Would like to lead with fewer expectations than implied greater expectations..  

**Brent Zundel:** the words non-exhaustive selection of registries is in the PR so this does not tie us to anything..  

> *Kyle Den Hartog:* yeah I saw that, but that's where I was thinking that by still explicitly stating them we're setting expectations from the outset which I don't believe is necessary at this point.

**Joe Andrieu:** before we enshrine any particular registries i think we should put in the charter, before we name any such registries, exactly what we mean by permissive..  

> *Oliver Terbu:* +1 joeandrieu.

> *Manu Sporny:* +1 to Joe.

**Joe Andrieu:** would like to enshrine the concepts of permissiveness and non-exhaustiveness.  

**Manu Sporny:** i'd like ot push this PR a bit more, im hearing you're opposed to it, will you object? I think we need to settle if we're putting this kind of language in, i'd like to hear why the registries section compared to the other sections. Being vague hurt us in the did-wg, it would be best to have the discussion now, and at least come up with a core set. these are MAYs and we shouldn't have issues at CR or REC.  

**Kyle Den Hartog:** i wouldn't formally object, and I don't think i can due to invited expert status. my intent is to see it be done in a way as inclusive as possible.  

**Kristina Yasuda:** we do have a strong objection from mike, though he is not on this call; I'm not sure if it will lead to FO but I know he has strong objections..  
… I think a statement that lets put this in because it might lead to less future objections, theres already a may, and if you interpret it as it is, you can include anything, and theres nothing out of scope. You can't say anything is out of scope. I think hearing objections of joe and kyle, I think the may statement strikes a good balance.  

> *Orie Steele:* -1 to the suggestion that "being vague" is a good idea... we have plenty of evidence that is a bad idea..

> *Kristina Yasuda:* that's why I said, I cannot speak for Mike.  
> I did not say he *would*.

**Manu Sporny:** I don't think that speaking for others is not a good mode of communication. If mike isn't gonna be here then anyone speaking on his behalf is problematic, and potentially stops us from reaching consensus. If people will object they need to be in the group or write to the group.  

> *Kristina Yasuda:* "I said he might but I cannot speak for him".  
> please do not twist what I said.

> *Manu Sporny:* Not trying to twist what you said -- "he might" is in the same class of statement..

> *Manu Sporny:* Ok, well, if we're going to take that approach, then we can't talk about registries today, can we?.

**Kyle Den Hartog:** I know mike has an opinion and it seems he has the strongest opinion, can we come back to this on later weeks?.  

</details>

**Comment by brentzundel** [comment]
General agreement on the call to close this PR. Meeting notes to follow.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2022-03-16-vcwg#section3-1) on 2022-03-16

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 3.1. A non-exhaustive set of possible registries (pr vc-wg-charter#99)

_See github pull request [vc-wg-charter#99](https://github.com/w3c/vc-wg-charter/pull/99)._




**Brent Zundel:** First PR to look at is #99.  
… This PR takes the section where registries are listed and adds a non-exhaustive selection of registries the WG *may* wish to produce.  
… We've had back and forth on this PR, pretty clear opposition from some folks who feel it's unnecessary. This is the conversation we're having now.  

**Michael Jones:** I think that the registries that we create should come out of normative work that we do. They can organically evolve throughout the life of the WG. Thanks to Brent for already creating and merging the PR that says registries are in scope and we can decide what to add along the way.  
… I think, if anything, a laundry list of registries could create problems and arguments in the group around not following the list.  

**Brent Zundel:** I didn't originally agree with you, Mike. I liked the symmetry of having the tables with the other sections. But having recently re-read the charter and to get to the registries section and just have a couple of lines there that says "we might do registries" is kind of a relief.  

**Dave Longley:** I'm not speaking in favor of the list in this PR. but I would like to address people's concerns.  
… I think what they're worried about - anything in that list is not available to be put into the WG in time.  
… but whatever's in that list, someone might say "well, that wasn't ever in scope".  
… but if we point to this GH issue, we can say, when we were making the decision, we were not ruling out anything in that list.  

**Orie Steele:** I agree with Mike and Dave and Brent.  
… Getting to that part of the charter is good without that list. We need to remember we might create a registry or we might not. That's what "we might do registries" means -- and it also means we might not. As long as we all agree that we might or might not do registries we're all fine.  
… The meeting minutes will show that we might do any number of registries, we might not -- we talked about all this. As long as that's well understood, we're good.  

**Brent Zundel:** So we have agreement that we probably shouldn't merge #99. So we will not.  
… Let's look at #100.  

**Michael Jones:** Can we close PR 99, having made a decision?.  

**Brent Zundel:** I was planning on closing it as soon as the minutes of today were recorded.  

**Michael Jones:** That's acceptable.  

</details>

**Pull request closed without merging**
