### PR TITLE
Add second chair information

### PR DESCRIPTION
**Pull request by brentzundel**
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-wg-charter/pull/41.html" title="Last updated on Jan 19, 2022, 12:02 AM UTC (51d497d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-wg-charter/41/50643d5...51d497d.html" title="Last updated on Jan 19, 2022, 12:02 AM UTC (51d497d)">Diff</a>

### CODE REVIEW

**Comment by brentzundel** [comment]
@Sakurann

**Review by Sakurann — APPROVED** [review]

**Comment by David-Chadwick** [comment]
Good choice!

**Review by iherman — APPROVED** [review]

**Review by clehner — APPROVED** [review]

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2022-01-19-vcwg#section5-2) on 2022-01-19

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 5.2. Add second chair information (pr vc-wg-charter#41)

_See github pull request [vc-wg-charter#41](https://github.com/w3c/vc-wg-charter/pull/41)._




**Brent Zundel:** with that, we have two PRs to look at it. the first one is PR 41.  
… proposal to add Kristina Yasuda from Microsoft as the next co-chair for the WG.  

**Wayne Chang:** I want to speak in support of Kristina/Microsoft taking a chair position..  
… With their interested in the VC spec, we can move towards production readiness and satisfying customers..  
… it's a balance to get different ecosystems conforming to a data model..  
… Very impressive contributions, looking forward to it..  

**Brent Zundel:** please add your checkmarks to the PR itself, if no more comments please move to the other PR.  

</details>

**Review by kdenhartog-mattr — APPROVED** [review]

**Review by kdenhartog — APPROVED** [review]
+1 from me to have @Sakurann take the second chair position - @kdenhartog-mattr is me as well, so please don't count those separately.

**Review by selfissued — APPROVED** [review]

**Pull request merged**
