### PR TITLE
Add ACLU as liaison.

### PR DESCRIPTION
**Pull request by msporny**
Some of us have been speaking with the ACLU about VCs and their potential over the last year. This PR furthers that relationship and establishes a more formal one between the ACLU and the VCWG. 

The goal here is to enable the ACLU to provide input and guidance to the VCWG from a civil liberties perspective.

Doing this would be a wise step for the VCWG because of the concerns that they have raised with the way that mDL is expected to be deployed and the very public way those concerns came to light. While VCWG has more options from a privacy preservation perspective than mDL does, it is imperative that the group get more regular feedback on how we're doing as we refine the Verifiable Credentials technology.

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-wg-charter/pull/69.html" title="Last updated on Feb 4, 2022, 12:25 AM UTC (7d08287)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-wg-charter/69/9a2a8d1...7d08287.html" title="Last updated on Feb 4, 2022, 12:25 AM UTC (7d08287)">Diff</a>

### CODE REVIEW

**Review by iherman — APPROVED** [review]

**Review by mprorock — APPROVED** [review]
Thanks for taking the initiative on this @msporny

**Review by OR13 — APPROVED** [review]

**Review by brentzundel — APPROVED** [review]

**Review by mkhraisha — APPROVED** [review]

**Review by kdenhartog — APPROVED** [review]

**Comment by Sakurann** [comment]
What is an official step for a W3C WG to have a liaison with an external organization? I assume adding to the charter is not enough? Or is ACLU already a liaison?

**Review by Sakurann — APPROVED** [review]

**Comment by iherman** [comment]
> What is an official step for a W3C WG to have a liaison with an external organization? I assume adding to the charter is not enough? Or is ACLU already a liaison?

At this point, adding it to the charter is enough. If the charter is voted and the WG is operational, we would have to contact the ACLU and see with them what is the level of "liaison" that we mutually want to establish. It may be as simple as an agreement between the groups, and it can be as formal as a liaison between that organization and the W3C in general on specific subjects (see, just as an example, the [list of liaisons of W3C](https://www.w3.org/2001/11/StdLiaison.html)).

(Personally, I do not think it is necessary to "elevate" that on a W3C level, but let's cross that particular bridge if and when we get there.)

**Comment by iherman** [comment]
@brentzundel or @Sakurann, would you do the honor of merging this PR?

**Comment by msporny** [comment]
> we would have to contact the ACLU and see with them what is the level of "liaison" that we mutually want to establish.

To be clear, I have been in contact w/ the ACLU and they have said they're interested.

**Review by brentzundel — APPROVED** [review]

**Comment by brentzundel** [comment]
multiple positive reviews, merging

**Pull request merged**
